sign-commit = true
sign-tag = true
push = true
publish = false
no-confirm = true
tag-prefix = "v"
consolidate-commits = true
tag-message = "chore: release {{version}}"
pre-release-hook = [
  "git",
  "cliff",
  "-c",
  "github",
  "-o",
  "CHANGELOG.md",
  "--tag",
  "{{version}}",
]
